name: Terraform Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Debug Step: List the directory structure to confirm files
      - name: List Files
        run: ls -R

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # Initialize Terraform
      - name: Terraform Init
        run: terraform -chdir=terraform init

      # Plan Terraform changes
      - name: Terraform Plan
        run: terraform -chdir=terraform plan -out=tfplan

      # Apply Terraform changes
      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve tfplan
